name: Generate/Upload D2 Diagrams

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

jobs:
  generate_diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up D2
        run: |
         curl -fsSL https://d2lang.com/install.sh | sh -s --
      - name: Generate D2 diagrams
        run: ./scripts/generate_d2_pngs.sh
      - name: Upload D2 Diagrams
        uses: actions/upload-artifact@v4
        with:
          name: D2 Diagrams
          path: ./architecture/*.png